version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: training1_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
