version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: training1_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  todo-backend:
    image: node:18
    volumes:
      - "./backend:/app"
      - "./entrypoint.sh:/entrypoint.sh"
    working_dir: "/app"
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    entrypoint: "/entrypoint.sh"

  todo-frontend:
    image: node:18
    volumes:
      - "./frontend:/app"
    working_dir: "/app"
    ports:
      - "3000:3000"
    entrypoint: "npm start"
